### ISSUE TITLE
NVAPI usage by Unreal Engine 4

### ISSUE THREAD

**Issue by K0bin** [jp7677/dxvk-nvapi#1]
List of NvAPI functions that UE4 uses:

NvAPI_Initialize
NvAPI_Unload
NvAPI_D3D1x_BindSwapBarrier
NvAPI_D3D1x_JoinSwapGroup
NvAPI_D3D1x_QueryMaxSwapGroup
NvAPI_D3D1x_Present
NvAPI_EnumPhysicalGPUs
NvAPI_GPU_GetPstates20
NvAPI_D3D11_IsNvShaderExtnOpCodeSupported
NvAPI_D3D_GetCurrentSLIState
NvAPI_Disp_GetHdrCapabilities
NvAPI_Disp_HdrColorControl
NvAPI_DISP_GetDisplayIdByDisplayName
NvAPI_GetErrorMessage
NvAPI_D3D12_CreateGraphicsPipelineState
NvAPI_D3D12_CreateComputePipelineState
NvAPI_D3D12_IsNvShaderExtnOpCodeSupported
NvAPI_D3D_GetObjectHandleForResource
NvAPI_D3D_BeginResourceRendering
NvAPI_D3D_EndResourceRendering
NvAPI_D3D11_SetDepthBoundsTest
NvAPI_D3D11_BeginUAVOverlap
NvAPI_D3D11_EndUAVOverlap
NvAPI_D3D_SetResourceHint
NvAPI_D3D11_SetNvShaderExtnSlot

Just putting this here, so it does not get drowned on Discord.

**Comment by jp7677** [comment]
Thanks a lot. From discord, this is the list of used methods for UE4 master (July 2020).

**Comment by jp7677** [comment]
UE4 4.22, which is used by ACC, seems to use:
- NvAPI_Initialize
- NvAPI_Unload
- NvAPI_GetErrorMessage
- NvAPI_DISP_GetDisplayIdByDisplayName
- NvAPI_D3D_GetCurrentSLIState
- NvAPI_D3D_GetObjectHandleForResource
- NvAPI_D3D_SetResourceHint
- NvAPI_D3D11_IsNvShaderExtnOpCodeSupported
- NvAPI_D3D11_SetDepthBoundsTest
- 0x33c7358c (NvAPI_Diag_ReportCallStart?)
- 0x593e8644 (NvAPI_Diag_ReportCallReturn?)

This is the set that is currently implemented which essentially ensures that UE4 uses `SetDepthBoundsTest`.

**Comment by jp7677** [comment]
From the D3D11 methods these two are also now implemented (I mean forwarded to DXVK):

- NvAPI_D3D11_BeginUAVOverlap
- NvAPI_D3D11_EndUAVOverlap

Please let me know if you see a tech demo or similar that uses these methods.

**Comment by jp7677** [comment]
Using this settings in an `Engine.ini` might be needed for UE4 to use Begin/EndUAVOverlap.

```
[/Script/Engine.RendererSettings]
r.D3D11.NVAutoFlushUAV=1
```

I haven't tested this yet though.

**Comment by sfjuocekr** [comment]
EnableUAVOverlap:
```
This function is called after every draw or dispatch to turn overlap back on if it was turned off by a UAV barrier.
This way, the next draw/dispatch after the barrier executes after everything before it has completed and the caches were flushed, and any subsequent submissions are allowed to overlap until the next UAV barrier.
```

DisableUAVOverlap:
```
This is called when a transition to UAVCompute or UAVGraphics is executed.
It disables overlapping for the next draw/dispatch, so we get the same behavior as with a UAV barrier in APIs with explicit barriers.
Overlapping will be turned back on automatically after the draw/dispatch.
```

**Comment by jp7677** [comment]
> It is called without any checks.

I'm reading what you wrote, but I don't understand what you are trying to say. Could you please rephrase?

**Comment by sfjuocekr** [comment]
If you add yourself to the Unreal Organization on github, you can browse the source and find where the functions are used.

Engine/Source/Runtime/Windows/D3D11RHI/Private/D3D11Commands.cpp is where you want to look.

**Comment by jp7677** [comment]
So you are saying that `r.D3D11.NVAutoFlushUAV=1` is not relevant?

**Comment by Skierman** [comment]
Not sure if this is related but could this be used to get UE5's Nanite feature to work?

**Comment by jp7677** [comment]
> Not sure if this is related but could this be used to get UE5's Nanite feature to work?

As far as I know, Nanite unfortunately requires either Nvidia or AMD specific shader functions. See e.g. https://developer.nvidia.com/unlocking-gpu-intrinsics-hlsl how this is supposed to work for Nvidia with D3D11 or D3D12. Currently this project just reports that none of those functions are supported (e.g. .https://github.com/jp7677/dxvk-nvapi/blob/master/src/nvapi_d3d12.cpp#L18)

Supporting this by using NVAPI would indeed need work here. Though most (nearly all) of the magic needs to happen in VKD3D-Proton. From my understanding this is really not a trivial thing to do.

**Comment by jp7677** [comment]
ACC 1.8 is out with an update to UE4 4.26.2 inkl. DLSS.  
I'm seeing SDBT and UAV overlap in the logs, DLSS is also working fine.

To summarize, I guess we are good with regards to UE4.
