### ISSUE TITLE
Does Proton experimental 7+ still need PROTON_ENABLE_NVAPI=1

### ISSUE THREAD

**Issue by luisalvarado** [jp7677/dxvk-nvapi#105]
Wanted to ask the guru here about this step

Proton 6.3-6 and newer includes DXVK-NVAPI but it is disabled by default.

Use PROTON_ENABLE_NVAPI=1 as game launch argument in Steam to enable DXVK-NVAPI. Use additionally PROTON_HIDE_NVIDIA_GPU=0 for certain titles that don't rely on D3D for obtaining the current GPU type and have this Proton setting applied.
Copy and replace nvapi.dll/nvapi64.dll into the dist/lib/wine/nvapi/dist/lib64/wine/nvapi folder of your Proton installation, e.g. in ~/.steam/steam/steamapps/common/Proton 7.0/ if you want to manually update the included version

Is this still needed for proton experimental. Am using bleeding edge. And if so, is there a game I can test to see the difference between having it and not enabling it?

I was doing some videos at https://www.youtube.com/@xtremelinux but I want to make sure if I talk about this, I do not make any mistakes explaining the benefits and what is used for. Thank you.

**Comment by luisalvarado** [comment]
> 

Thank you so much for clearing a lot of stuff. Not only that but the additional information will also help so thank you again. So at the end, the end user still needs to set PROTON_ENABLE_NVAPI=1 but no need for the other one correct?

**Comment by jp7677** [comment]
> So at the end, the end user still needs to set PROTON_ENABLE_NVAPI=1 but no need for the other one correct? 

Correct. That said, you only need to set `PROTON_ENABLE_NVAPI=1` for Proton Experimental if you want to use it for games that are not in aforementioned list. Note that unconditionally enabling DXVK-NVAPI might also break games, e.g. `Guardians of the Galaxy`. So there is still a minimal risk involved. 

(PS: Please also read the first chapter in the readme about what DXVK-NVAPI is, and more important, what it is not. Its actually a very thin layer. The actual magic lives in DXVK/VKD3D-Proton and in the drivers.)

**Comment by luisalvarado** [comment]
Why thank you very much my good sir. I will go over everything as instructed. Thank you for the time and quality answers.
