### ISSUE TITLE
Hellblade: Senua's Sacrifice VR Edition crash when `PROTON_ENABLE_NVAPI=1`

### ISSUE THREAD

**Issue by gareth-anthony-hulse** [jp7677/dxvk-nvapi#113]
Was recommended to report here. Originally I brought up the issue at https://github.com/ValveSoftware/Proton/issues/4370.

Error message as soon as game starts:
 ![Screenshot_20230318_113223](https://user-images.githubusercontent.com/107568353/226103018-707d17e6-6c3a-4627-ad22-4d268f24ac50.png)

Log output with `PROTON_LOG=1 %command%` as launch option: [steam-747350.log](https://github.com/jp7677/dxvk-nvapi/files/11026176/steam-747350.log)

When launch option is set to `PROTON_ENABLE_NVAPI=0 %command%` the game works without issue. I have `PROTON_ENABLE_NVAPI=1` in `/etc/environment` just to avoid adding it to every game's launch option. 

**Specs:** https://linux-hardware.org/?probe=d32441b2c3
**SteamVR version:** 1.25.6

**Comment by jp7677** [comment]
Thanks for the report, could you try this PR https://github.com/jp7677/dxvk-nvapi/pull/114 ? It should let the VR edition start. I haven't my headset currently attached, so I could not enter the game and verify that it actually works.

You can grab a build from GitHub actions, https://github.com/jp7677/dxvk-nvapi/actions/runs/4482562149

**Comment by gareth-anthony-hulse** [comment]
I used the build from GitHub actions and it has fixed the issue.

**Comment by jp7677** [comment]
Nice, thanks for the confirmation. I’ll complete this PR and land it on master, probably on Friday.
