### ISSUE TITLE
Unigine Superposition through dxvk: No Temperature shown with 0.6.2

### ISSUE THREAD

**Issue by tisim** [jp7677/dxvk-nvapi#116]
Graphics Card MSI RTX 2080 Gaming X Trio.
Kernel 6.2.x (several in 6.2 tested)
dxvk: several different versions tested
driver: 525.47.13 and 530.41.03
wine: several versions tested from 8.0.4 Staging to Wine Proton GE

Observed behaviour:
When starting the Windows Version of Unigine Superposition through lutris (wine/dxvk) with dxvk-nvapi 0.6.2 Temperature is missing in the top right corner and in the result. (maybe some other sensor as well)

Selecting a prior version in lutris (0.5.4) will show temperatures just fine.

**Comment by Saancreed** [comment]
That seems to be a bug in Lutris package/release of dxvk-nvapi v0.6.2, it should include both `nvml.dll` and `nvml.so` for temperatures to work but it only has the former.

**Comment by jp7677** [comment]
@tisim Thanks for the report. 

What Saancreed said, could you please open an issue at the Lutris issue tracker. Lutris needs to follow the instructions for wine-nvml 0.2 ( https://github.com/Saancreed/wine-nvml#installing ), those are different for 0.2 i.c.w. Wine/Proton > 7.0 than for the older 0.1 version.

**Comment by tisim** [comment]
Hi, 
sorry for reacting late. I was already in contact and forgot to update here.
