### ISSUE TITLE
How can I use DXVK-NVAPI in windows?

### ISSUE THREAD

**Issue by Ieandro** [jp7677/dxvk-nvapi#129]
I currently play Hogwarts Legacy with DXVK and VKD3D -PROTON and my FPS are stable above 60 all the time, I play in 1080p, and with DX12 my fps drop a lot in several areas because my gpu and cpu never go up to 70%, so with vulkan I can use all my hardware, but I would like to be able to use DLSS and play in 1440p with dlss in quality, actually when I use AMD FSR2 in quality my fps are more stable than in native 1080p, but it looks ugly, so I prefer native 1080p, my settings are a mix of medium with high, but I would like to use DLSS in quality with 1400p, because if it gives me the same fps as in AMD FSR2 but with a better visual image I would use it, I just don't know how to activate DXVK-NVAPI in Windows.

**Comment by jp7677** [comment]
^^^ what K0bin wrote. The NVIDIA driver for Linux comes with some extra bits for supporting DLSS for DXVK / VKD3D-Proton, this unfortunately won't work on Windows as far as I'm aware.

**Comment by Ieandro** [comment]
So I have no way to use dlss on windows with vulkan? Too bad, I was excited thinking that I could.

**Comment by K0bin** [comment]
Yes, DLSS does not work with DXVK or VKD3D-Proton on Windows. It has nothing to do with Vulkan though, it works fine in Doom Eternal which uses Vulkan.
