### ISSUE TITLE
Screen corruption in Cyberpunk 2077 with GOG overlay

### ISSUE THREAD

**Issue by pppbb** [jp7677/dxvk-nvapi#136]
![2023-08-05_0237_1](https://github.com/jp7677/dxvk-nvapi/assets/33740721/bebec16f-4b4d-409a-8b80-7a25f4c047c0)
![2023-08-05_0238_8](https://github.com/jp7677/dxvk-nvapi/assets/33740721/035a46e2-8d92-4259-912c-cdc1d1df39e0)
There are triangle artifacts around some of the objects drawn on screen. But only with nvapi.

**Comment by pppbb** [comment]
UPDATE:I observed the same problem in Destroy All Humans!.

**Comment by jp7677** [comment]
I guess you mean the dark gray spots/squares in your screenshots? I don't see them on my system when running the CP benchmark with latest DXVK/DXVK-NVAPI/VKD3D-Poton.

Is this dependent on certain graphics settings (e.g. with/without DLSS, with/without RTX)? Could you also share some details about your system and the game environment?

**Comment by pppbb** [comment]
OS: Arch Linux
Lutris latest
wine-GE-Proton8-13
vkd3d-proton latest
NVIDIA Geforce rtx 4080
Cyberpunk 2077 1.63
ultra settings with rtx on and off dlss on and off
no problems without nvapi loaded
NVIDIA 535.86.05
NVAPI 0.6.3
Please dont hesitate to ask for more info.

**Comment by pppbb** [comment]
UPDATE: I discovered that corruption happens only when gog overlay is enabled.

**Comment by jp7677** [comment]
> UPDATE: I discovered that corruption happens only when gog overlay is enabled.

Thanks a lot for figuring this out. Actually I'm tending to blame the overlay in doing something that doesn't play well. With RTX and DLSS off, NVAPI isn't really doing much except providing some topology and system info (like driver version) to the game. There are afaik no more NAPI calls after the game finishes initializing.

Could you please try hiding DXVK-NVAPI but also disabling the DXVK AMD spoofing (aka the DXVK `nvapiHack`)? I'm not sure though if the game still successfully starts when it sees an NVIDIA card, but cannot load NVAPI.

**Comment by pppbb** [comment]
> I'm not sure though if the game still successfully starts when it sees an NVIDIA card, but cannot load NVAPI.

It starts fine.

**Comment by jp7677** [comment]
> > I'm not sure though if the game still successfully starts when it sees an NVIDIA card, but cannot load NVAPI.
> 
> It starts fine.

I assume the artifacts are also gone when starting without NVAPI and without nvapiHack? In that case could you please provide DXVK logs when starting the game without NVAPI and without the nvapiHack being enabled.
Could you please also provide DXVK-NVAPI logs (see <https://github.com/jp7677/dxvk-nvapi#tweaks-debugging-and-troubleshooting>) with DLSS off and RTX off?

**Comment by jp7677** [comment]
@pppbb is this still an issue?

**Comment by jp7677** [comment]
Feel free to reopen if something new comes up.
