### ISSUE TITLE
100% repro crash in Shadow Warrior 3

### ISSUE THREAD

**Issue by pppbb** [jp7677/dxvk-nvapi#138]
To reproduce enable nvapi in wine/proton (dlss on or off) and load savegame.

**Comment by Saancreed** [comment]
Please switch Proton version to Experimental _Bleeding Edge_, run the game with `PROTON_ENABLE_NVAPI=1 PROTON_LOG=1 DXVK_NVAPI_LOG_LEVEL=info %command%` as launch options and post the log file created in your home directory.

**Comment by pppbb** [comment]
[steam-10990728036692787200.log.txt](https://github.com/jp7677/dxvk-nvapi/files/12271044/steam-10990728036692787200.log.txt)

**Comment by pppbb** [comment]
With proton experimental and no dlss - no hangs.

**Comment by pppbb** [comment]
I solved the problem. It was my fault(crashes). DXVK-NVAPI works fine.
