### ISSUE TITLE
nvapi does not work in wine 9 with winewayland.drv driver enabled

### ISSUE THREAD

**Issue by ghost** [jp7677/dxvk-nvapi#150]
A few hours ago the stable release of Wine 9.0 was released, which added an experimentation of running natively under wayland without xwayland, I decided to check it out by playing a game

As an example, I had Alan wake II, and running it, I noticed that features such as DLSS were missing from the game settings, and some of the RT features, I decided to run the game again but in x11, and settings such as DLSS became available

How to check

1. Use wine 9.0
2. Make sure what you enabled Wayland driver 
`wine reg.exe add HKCU\\Software\\Wine\\Drivers /v Graphics /d x11,wayland` 
and and then making sure that the DISPLAY environment variable is unset,  
3. Make sure that nvapi is enable
3. Run game who supports nvidia stuff (DLSS for example) under wayland session
4. Go to the game settings and you will see that there is no DLSS function, only FSR (if the game supports)

- I used the "Bottles" to run the game

Additional information that may be helpful
- Kernel: 6.7.0-zen3-1-zen
- Distro Arch Linux
- GPU: NVIDIA GeForce RTX 4060 Ti 16GB
- Driver open-dkms driver nvidia [545.29.06]
- DE Gnome
- Latest dxvk-nvapi [0.6.4]
- vkd3d-proton-2.11.1

**Comment by jp7677** [comment]
Thanks for the report. Interesting. Could you please try to fetch and post log files from dxvk-nvapi with x11 and with Wayland. See https://github.com/jp7677/dxvk-nvapi#tweaks-debugging-and-troubleshooting

**Comment by AlexeySFr** [comment]
> Thanks for the report. Interesting. Could you please try to fetch and post log files from dxvk-nvapi with x11 and with Wayland. See https://github.com/jp7677/dxvk-nvapi#tweaks-debugging-and-troubleshooting

I think I should close the problem, as now I have nvapi now not working at all, on any version of wine, I think I was in a hurry to create this report here, sorry for possibly misinformation.

**Comment by jp7677** [comment]
No worries, feel free to reopen if something new comes up.

**Comment by oscarbg** [comment]
similar issue but even with no winewayland.drv..
seeing logs of vk_streamline app on X11 vs Wayland I see new errors in Wayland in DXVK logs:
```
warn:  DXGI: Found monitors not associated with any adapter, using fallback
info:  Adapter LUID 0: 0:3f6
err:   readMonitorEdidFromKey: Failed to get EDID reg key size
err:   DXGI: Failed to parse display metadata + colorimetry info, using blank.
```
not present in X11..

which lead to streamline logs in Wayland:
```
[07.03.2024 03-51-03][streamline][info]commoninterface.cpp:261[getSystemCaps] NVIDIA driver 550.40
[07.03.2024 03-51-03][streamline][error]commoninterface.cpp:271[getSystemCaps] NvAPI_GPU_GetLogicalGpuInfo(hLogicalGPU, &lData) failed error -1
```
vs on X11:
```
[07.03.2024 03-48-31][streamline][info]commoninterface.cpp:261[getSystemCaps] NVIDIA driver 550.40
[07.03.2024 03-48-31][streamline][info]commoninterface.cpp:286[getSystemCaps] Adapter 0 architecture 0x190 implementation 0x2 revision 0xffffffff - bit 0x1 - LUID 0.1010

```
