### ISSUE TITLE
dlss dxvk

### ISSUE THREAD

**Issue by BeersE22** [jp7677/dxvk-nvapi#225]
Hi, I would like to know the news of dlss for dxvk dx11 when you will put a support. I am sorry to disturb you

**Comment by K0bin** [comment]
DLSS has worked with DXVK for years.

**Comment by SheMelody** [comment]
> DLSS has worked with DXVK for years.

They mean with DirectX 11 apparently. Not many games (almost none of them) use DLSS in DirectX 11.

**Comment by Blisto91** [comment]
Yes dx11 games that support dlss upscaling works with dxvk when used together with dxvk-nvapi

**Comment by SheMelody** [comment]
> Yes dx11 games that support dlss upscaling works with dxvk when used together with dxvk-nvapi

The only dx11 games that use DLSS (that I've ever played) are the ones from the GTA trilogy, and those unfortunately do not work with dxvk-nvapi. This could be a specific per-game compatibility problem.
@BeersE22 provide a specific game list

**Comment by BeersE22** [comment]
dlss does not work in grand theft auto trilogy while on windows it works, if you put dx12 it works

**Comment by Blisto91** [comment]
In which way does it not work? Originally i thought there was no option for it when i looked yesterday but trying again now i see a dlss option that can be enabled.

**Comment by SheMelody** [comment]
> In which way does it not work? Originally i thought there was no option for it when i looked yesterday but trying again now i see a dlss option that can be enabled (probably missed it the first time).

If you mean in GTA Trilogy, I have always thought that it just doesn't work. Says "DLSS (Unavailable)" for me, I don't know if @BeersE22 has the same or a different problem. I thought it was normal by the way, but I still don't want to derail this issue in particular which doesn't belong to me.

**Comment by BeersE22** [comment]
yes I get dlss (unavailable) work only vkd3d

**Comment by Blisto91** [comment]
How are you running the game. Through Steam with Proton?

**Comment by BeersE22** [comment]
proton ge/proton experimental i tried everything

**Comment by Blisto91** [comment]
Can you share a Proton log? Launch the game with `PROTON_LOG=1 %command%` in the games launch options. A log will appear in your users home folder.

**Comment by Blisto91** [comment]
Ok figured your issue.
The line of interest in your log is
```
37254.632:0634:0638:info:dxvk-nvapi:GPU Architecture overriden to AD100 via DXVK_NVAPI_GPU_ARCH, this will take precedence
```
which means that `DXVK_NVAPI_GPU_ARCH=AD100` is set somewhere. Dxvk-nvapi internally spoofs Ada GPUs as Ampere when certain older versions DLSS versions is detected because of a bug where it else won't allow it to be used. The variable will override this builtin workaround.
If i use `DXVK_NVAPI_GPU_ARCH=AD100` myself i can reproduce the issue too. 
Why it works in dx12 mode i don't know. Maybe the bug only affects the dx11 code.

**Comment by SheMelody** [comment]
I spoof ADA as well, I guess that's why it doesn't work for me either.
`DXVK_NVAPI_GPU_ARCH=GA100 ... %COMMAND%` should solve the problem I guess.

**Comment by Saancreed** [comment]
Or just… don't set it at all? The workaround is there for a reason and default behavior should just work™.

As a side note, I now regret adding this environment variable in the first place…

**Comment by SheMelody** [comment]
> Or just… don't set it at all? The workaround is there for a reason and default behavior should just work™.
> 
> As a side note, I now regret adding this environment variable in the first place…

IMHO, it's enough to just add a note in the readme.

**Comment by BeersE22** [comment]
> I spoof ADA as well, I guess that's why it doesn't work for me either. `DXVK_NVAPI_GPU_ARCH=GA100 ... %COMMAND%` should solve the problem I guess.

yes is work thanks i close the issue thanks to everyone
