### ISSUE TITLE
PhysX experimentation

### ISSUE THREAD

**Issue by SveSop** [jp7677/dxvk-nvapi#27]
I have done some experimentation with the demo "Fluidmark" [http://www.ozone3d.net/benchmarks/physx-fluidmark/](http://www.ozone3d.net/benchmarks/physx-fluidmark/) to figure out if i could get it to enable GPU based physx. So far not so good, but the staging implementation of nvapi/nvcuda does work with this demo.

I made a test implementation of what i suspect could be the nvapi call the demo uses - `NvAPI_GPU_CudaEnumComputeCapableGpus` (cos fiddling with this on the staging implementation will make it show "CPU only").
I also did a quick update to my tiny test proggy, and from comparing staging <-> dxvk-nvapi <-> windows, it shows that the `gpuhandle` part of what i am experimenting with is different. The staging implementation uses a "fake" id for this, as i guess they do not actually check any "real" gpu data like is done with dxvk-nvapi. I believe it is the demo that is outputting this error message:
`ERROR: Could Not Get Primary Adapter Handle`
(I cannot find this particular error message in the source)

I have not studied staging implementation of nvcuda in depth, but to me it kinda seems like a wrapper to libcuda.so (much like wine-nvml does), so i have hopes that it would work without changes.

[https://github.com/SveSop/dxvk-nvapi/tree/physx](https://github.com/SveSop/dxvk-nvapi/tree/physx)

Reason i started fiddling with this was that i have some vague memories of some game (Batman ?) that did not work with physx/nvapi, but ever since the default dxvk setting is to fake amd card it has not been a huge issue. I kinda thought that if dxvk-nvapi could make use of staging implementation of nvcuda for PhysX (for those games utilizing this) it could be some boost to perf?

Don't have any particular tests to perform, other than this Fluidmark demo i found so far.
Let me know if you think it is worth pursuing more, or if it is just a useless waste of time :)

EDIT: 
The implementation was missing `NvAPI_GetPhysicalGPUFromGPUID`. I've added that to my branch and a minor change to `NvAPI_GPU_CudaEnumComputeCapableGpus`

The Fluidmark demo now seems to work.

**Comment by EsdrasTarsis** [comment]
> I kinda thought that if dxvk-nvapi could make use of staging implementation of nvcuda for PhysX (for those games utilizing this) it could be some boost to perf?

I think it would be a good idea to implement nvcuda support in wine-nvml to make physx work on Proton

**Comment by SveSop** [comment]
> > I kinda thought that if dxvk-nvapi could make use of staging implementation of nvcuda for PhysX (for those games utilizing this) it could be some boost to perf?
> 
> I think it would be a good idea to implement nvcuda support in wine-nvml to make physx work on Proton

It does seem to work with the current implementation - ie. using nvapi/nvapi64 from dxvk-nvapi, and use the nvcuda++ libs from the staging implementation.

I was also able to get GPU physx in Batman Arkham City using Steam/Proton-6.12-GE-1 by using dxvk-nvapi and modifying nvcuda.c from staging to load `libcuda.so.1` instead of `libcuda.so`
Without going into too much detail on this, it is due to steam's "soldier/pressure-vessel" thing that isolates systemfiles in a particular way.

Doing some benchmarks sadly did not yield any particular performance increase by doing this, although i could see i had a wee bit less CPU usage, and a wee bit more GPU usage, however i seemed to only be able to get around 25-30% gpu usage at times, and around 30'ish % on CPU threads for some reason.

Will keep doing some tests and see if there is a benefit.

**Comment by jp7677** [comment]
Hi @SveSop, thanks for digging into this.

To summarize,  for the Fluidmark benchmark we need to implement the following methods:
- `NvAPI_GPU_CudaEnumComputeCapableGpus`
- `NvAPI_GetPhysicalGPUFromGPUID` (we also include `NvAPI_GetGPUIDFromPhysicalGPU`)

Correct?

Regarding CUDA support, yeah, this is a project on its own, similar to wine-nvml but I guess more complex due to several interop things. I remember that the game Batman Arkham Knight uses CUDA directly for some physics related features ("Interactive Smoke and Fog" and "Interactive Paper Debries"), but therefore lots of work is needed for CUDA support in Wine, see https://github.com/doitsujin/dxvk/issues/788#issuecomment-442545872.
I don't know what Batman Arkham City does with PhysX, I would expect some additional features, but not so much performance improvements.

**Comment by SveSop** [comment]
> Hi @SveSop, thanks for digging into this.
> 
> To summarize, for the Fluidmark benchmark we need to implement the following methods:
> 
>     * `NvAPI_GPU_CudaEnumComputeCapableGpus`
> 
>     * `NvAPI_GetPhysicalGPUFromGPUID` (we should also include `NvAPI_GetGPUIDFromPhysicalGPU`)
> 
> 
> Correct? Implementing those seems trivial, but I would prefer to have them appear in the official NVAPI headers first.
> 
Yes. It did not seem as Batman Arkham City needed `NvAPI_GetPhysicalGPUFromGPUID` tho, so it might just be different implementations of this.
I do agree that it would be best for the correct implementation of this in the official nvapi headers tho, as i had to create a separate header with the struct needed for `NvAPI_GPU_CudaEnumComputeCapableGpus`. (Well.. "had to".. could just as easily dropped it in some other header tho).

> Regarding CUDA support, yeah, this is a project on its own, similar to wine-nvml but I guess much more complex due to several interop things (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__D3D11.html). I remember that the game Batman Arkham Knight uses CUDA directly for some physics related features ("Interactive Smoke and Fog" and "Interactive Paper Debries"), but therefore lots of work is needed for CUDA support in Wine, see [doitsujin/dxvk#788 (comment)](https://github.com/doitsujin/dxvk/issues/788#issuecomment-442545872).
> I don't know what Batman Arkham City does with PhysX, I would expect some additional features, but not so much performance improvements.

I have only tested Arkham City and Fluidmark so far, and enabling PhysX with the aforementioned functions + the change to staging `nvcuda.dll.so` loading `libcuda.so.1` instead of `libcuda.so` made it work with Proton (Same issue we had with `libnvml.so.1` and pressure-vessel).
Depending on implementation, i know Proton-GE already builds with staging nvapi implementation, and just replaces nvapi/nvapi64 when the option is "enabled" in the config, so nvcuda++ is "already there".

Imo, unless you absolutely WANT to re-implement this as a cpp thing included in dxvk-nvapi, i do not really see the need for starting this from scratch?

From what i understand of other benchmarks seen on youtube++, there is not a huge gain to fps to run physx on the GPU unless you have a dedicated GPU for that (Setting physx to "High" in the settings, shows that it recommends a dedicated physx card).
I currently do not have 2 nVidia gpu's in my machine, so it is kind of hard to actually test to see if it is possible to control this in any way (as Linux drivers does not seem to have any way to control this like the windows driver have).

You can see the difference of physx vs. none on Arkham City here: [https://www.youtube.com/watch?v=j7lr7B9k9SA](https://www.youtube.com/watch?v=j7lr7B9k9SA)
Quite a bit of smoke effects and debris are running on PhysX.

Ill keep doing some tests with other games and see how it works.

**Comment by jp7677** [comment]
Thanks for the youtube link about differences in Arkham City with various PhysX settings. From what I understand now, you can always set the PhysX settings to "high" in A-C like shown in the video, regardless of hardware support or not. For the latter, the CPU will take care of it with a performance penalty. With your patches, the GPU will do the PhysX math, but you don't see that much difference? Correct?
I have no plans to do something like wine-nvcuda, all I'm saying is that the current wine-staging implementation is not complete ;). It seems sufficient to support PhysX for Arkham City like generation of games, but lacks features for e.g. newer Arkham Knight. I guess implementing the missing bits and pieces is not that trivial.

**Comment by SveSop** [comment]
> Thanks for the youtube link about differences in Arkham City with various PhysX settings. From what I understand now, you can always set the PhysX settings to "high" in A-C like shown in the video, regardless of hardware support or not. For the latter, the CPU will take care of it with a performance penalty. With your patches, the GPU will do the PhysX math, but you don't see that much difference? Correct?

Yeah, pretty much. Although, from what i gather (and said above), that does not seem to be wine/linux/proton's fault, as you would most likely need a separate GPU to run physx on to see any real fps benefit.

> I have no plans to do something like wine-nvcuda, all I'm saying is that the current wine-staging implementation is not complete ;). It seems sufficient to support PhysX for Arkham City like generation of games (which is actually pretty cool), but lacks features for e.g. newer Arkham Knight. I guess implementing the missing bits and pieces is not that trivial.

I have not had the time to do any testing on Arkham Knight yet, but will report back my findings when i get there :)

**Comment by SveSop** [comment]
Installed Arkham Knight, and so far found that i had to add `NvAPI_GetGPUIDfromPhysicalGPU` aswell as adding a semi-stub to nvcuda - `cuD3D11GetDevice`

This would allow me to select both the PhysX options in the game settings - Smoke and debris, however the smoke part does not seem to work correctly (Benchmark does not show excessive smoke from the batmobile which i thought it would).

Will do more testing. So far from the logs it does indicate a few "unknown" functions are being logged, so ill see if i can dig around and figure out whats what there.

**Comment by jp7677** [comment]
> Installed Arkham Knight, and so far found that i had to add `NvAPI_GetGPUIDfromPhysicalGPU` aswell as adding a semi-stub to nvcuda - `cuD3D11GetDevice`

yeah, this is what I meant with the missing interop pieces in wine’s nvcuda. Since you stubbed it, it returns an error and the games seems to handle this gracefully. You might wanna try to implement that function and just return the first cuda device (not sure how easy this is, I haven’t looked into the source). But then you’ll probably run into the next unimplemented things…

**Comment by SveSop** [comment]
It does not return an error, but it returns the `pCudaDevice` (hence it is called a semi-stub in the source.. basically the same that was done for `cuD3D10GetDevice` originally, since in the headers they reference the same.

This might not always be true, especially if/when we are talking about multiple adapters ofc.
```
FIXME("(%p, %p) - semi-stub\n", pCudaDevice, pAdapter);
/* DXGI adapters don't have an OpenGL context assigned yet, otherwise we could use cuGLGetDevices */
return pcuDeviceGet(pCudaDevice, 0);
```
The comment thus seems to indicate doing what you said - just return the first cuda device, but hint at the "more correct function" probably would be to get devices from dxgi or similar.

There is also some structs that seems to be "unknown", that contains some sort of data structure that is being compared to the loaded library (i would assume), and if the structure that is generated is <> what is implemented in the library, this is being informed:
```
    if (orig->size > impl->size)
    {
        FIXME("WARNING: Your CUDA version supports a newer interface for %s then the Wine implementation.\n", name);
    }
    else if (orig->size < impl->size)
    {
        FIXME("Your CUDA version supports only an older interface for %s, downgrading version.\n", name);
        impl->size = orig->size;
    }
```
For "unknown1" this warning line is dropped, this indicating that "unknown1" structure contains > than the wine source. How to dig though this, i dunno, but ill keep looking.

PS. In my "for-dummies" understanding, i would kinda conclude that if you have newer CUDA implementation than 7.0 (currently 11.4) this would be the case, and Arkham Knight might just need CUDA 8 perhaps - thinking about release year (and the 372.54 driver mentioned in the link below implement CUDA 8.0)

[https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/238054/physx-particle-effects-not-working/](https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/238054/physx-particle-effects-not-working/)
Does hint at "install the standalone PhysX package". I installed the winetricks version, which is 9.14. This might be too old aswell perhaps?

**Comment by SveSop** [comment]
Update:
I think my suspicions were correct. I updated the PhysX package to 9.19 (running the .exe with protontricks shell), and wham.. crash on missing function: `cuGraphicsD3D11RegisterResource`

I further suspect this is needed for interactive smoke, as when playing and using my batarang (or whatsitsname), i would suspect this could cause a small puff of smoke - and it crashes when i do that. Also the benchmark that did not have any smoke with PhysX 9.14 crashed immediately.

Ill update this if i gain some progress, although looking briefly at the structures of this call, i fear i am way out of my league here...

**Comment by SveSop** [comment]
Update: Smoke baby! :+1: 
Ait.. added a semi-stub for `cuGraphicsD3D11RegisterResource` basically following the directions from cudaD3D11.h:

> If \p pD3DResource cannot be registered then ::CUDA_ERROR_UNKNOWN is returned.

So i did that. Tried with CUDA_SUCCESS too, but that seemed to be a bit more spammy on the logs, and tbh atm i do not know how to make cuda register any resources with d3d11 without involving something transitional to dxvk or something like that. Returning `CUDA_ERROR_UNKNOWN` is more or less "correct" to do, since the resource cannot actually be registered.

Does give smoke and moving debris now atleast. Will keep testing to see if there is any random crashes or stuff tho.

**Comment by jp7677** [comment]
Oh, wow, this is actually really cool, congratulations!
Since you used the word “stubbed”, I assumed you really just added the method entry point (https://en.wikipedia.org/wiki/Method_stub), but actually you implemented `cuD3D11GetDevice`. Cool to read that this was more or less straight forward and returning an error code from `cuGraphicsD3D11RegisterResource` is sufficient. I thought there would be more to it, but cool that I was proven wrong. 
Could you try to get those 2 cuda methods into wine-staging? Let’s wait a bit for the next nvapi headers look like, depending on that we can decide a route for dxvk-nvapi.

**Comment by SveSop** [comment]
I used the word "stubbed" cos the functions for D3D9 and D3D10 already in the source was a FIXME - semi-stub. I kinda understand this as a "not completely working function" - and thus a "semi" stub. What the result (other than making it actually work) would be for NOT "registering" resources, i can only imagine would be performance perhaps.

Not sure how to go about making a PR to staging, as it is not just to PR it on github. Submitting it to the wine mailinglist the incorrect way would probably mean it would fail, and if not picked up by the right ppl it will just drop into the "big black hole of useful ideas"...

Will check that out tho.

Getting the functions into the public nvapi headers might need reaching out to nVidia perhaps? Got any ideas?

**Comment by SveSop** [comment]
Oki.. according to [https://wiki.winehq.org/Wine-Staging_Contributing](https://wiki.winehq.org/Wine-Staging_Contributing) all staging patches must be submitted as bugs with a proposed patch attached.
Hopefully they will take a look at it and we shall see what happens.
[https://bugs.winehq.org/show_bug.cgi?id=51523](https://bugs.winehq.org/show_bug.cgi?id=51523)

**Comment by SveSop** [comment]
Upstream now: [https://github.com/wine-staging/wine-staging/commit/b059114710365d29b456e1f84d51d24810fa03b0](https://github.com/wine-staging/wine-staging/commit/b059114710365d29b456e1f84d51d24810fa03b0)

So, missing the dxvk-nvapi bits.

**Comment by jp7677** [comment]
Cool, thanks for the heads up. I’m away from my machine, though the bits and pieces here will follow.

PS: Since you testing Arkham Knight on Nvidia, is this issue https://github.com/doitsujin/dxvk/issues/580 still present when not spoofing an AMD card with Arkham Knight?

**Comment by SveSop** [comment]
> Cool, thanks for the heads up. I’m away from my machine for a few weeks, though the bits and pieces here will follow.
> 
> PS: Since you were testing Arkham Knight on Nvidia, is this issue [doitsujin/dxvk#580](https://github.com/doitsujin/dxvk/issues/580) still present when not spoofing an AMD card?

I have not noticed any crashes in "detective mode" so far. I assume the scene you posted here is where you enter the "clocktower" (or whatsitscalled) where you use detective mode to find the statue you tilt the head on to open the door? (I seem to remember something like that.)

When doing these tests i have used the dxvk setting: `dxgi.nvapiHack = False`

**Comment by jp7677** [comment]
> > Cool, thanks for the heads up. I’m away from my machine for a few weeks, though the bits and pieces here will follow.
> > PS: Since you were testing Arkham Knight on Nvidia, is this issue [doitsujin/dxvk#580](https://github.com/doitsujin/dxvk/issues/580) still present when not spoofing an AMD card?
> 
> I have not noticed any crashes in "detective mode" so far. I assume the scene you posted here is where you enter the "clocktower" (or whatsitscalled) where you use detective mode to find the statue you tilt the head on to open the door? (I seem to remember something like that.)
> 
> When doing these tests i have used the dxvk setting: `dxgi.nvapiHack = False`

Cool to read your reply. I guess the initial issue has been resolved somewhere in the stack for Nvidia.

**Comment by jp7677** [comment]
@SveSop  you could try to upstream your change about the adjusted library name too (the .1 thingie). It seems a correct change to me, similar like with nvml.

**Comment by SveSop** [comment]
> @SveSop you could try to upstream your change about the adjusted library name too (the .1 thingie). It seems a correct change to me, similar like with nvml.

I am a bit unsure unsure what my argument should be. As mentioned before - all staging changes they say have to come as a bugreport. What would be my "bug"?
"Steam/Proton does not load libraries unless they are loaded as .so.1"? Would "they" not just deem this as a "not our bug" thing, since this is proton specific?

I think i would have to go by the "using .so.1 is the more correct way" type of approach.

I will see if i can find some reputable linux arguments for this, and maybe use those, as i fear "this would make proton work" might not immediately fly.

**Comment by jp7677** [comment]
Yeah, I get what you mean. May be your angle could be versioning (prevent using an ABI incompatible version, though this is theoretical since there is no nvcuda.so.2 yet) and supporting containerized environments like Valves Pressure Vessel?

**Comment by Saancreed** [comment]
Looks like Liam just went ahead and submitted a patch for that himself :smile:
https://bugs.winehq.org/show_bug.cgi?id=51541

**Comment by SveSop** [comment]
Nice. (It is the same issue with nvencodeapi and nvcuvid, although not really used under steam/proton i would say).

> Though it's really worth examining whether we really want nvcuda in upstream Wine; and, if not, we should remove it from wine-staging.

This does not bode well tho. Maybe we end up having to build nvcuda together with dxvk-nvapi after all... Would probably not be a bad thing if the intent is to use dxvk-nvapi, cos that has zero chance of being upstreamed (g++ project after all). 

And what about nvml then? So far the only real usage is with nvapi, as there is no real point in running nvidia-smi.exe like tools under wine, when we can (and should for safety) use that directly in Linux.

Thoughts about consolidating DXVK-NVAPI with nvcuda + nvml as a single package source?

**Comment by jp7677** [comment]
@SveSop See https://github.com/jp7677/dxvk-nvapi/pull/34/files , this PR implements the three needed methods based on what I could find and by comparing with `nvidia-smi -q`. I could be horrible off due the still missing header update. Though if you want, you could give it a try by copying the method bodies into your fork. I would be interested if both the benchmark and the Arkham games still work with my assumptions.

Also note that there is a pending PR for Proton-Wine for including nvcuda (inkl. the `.so.1`).

**Comment by SveSop** [comment]
After fiddling with this a couple of hours.. i can't get it to work... I tend to use 10x the time to figure out weird changes when it comes to CPP, instead of the usual 5x the time with C

Need a break.. Will get some shuteye and see if i can figure it out tomorrow :+1:

**Comment by jp7677** [comment]
@SveSop As follow up from discord, happy to read that you found the typo. See https://github.com/jp7677/dxvk-nvapi/commit/f4659ca4ce7e00a5a83b41a06535460721f8da74 to prevent having to hunt for typos in method names in the future.

**Comment by SveSop** [comment]
Nice! This will safeguard when adding new functions 👍

**Comment by SveSop** [comment]
@jp7677 Not to be a killjoy here.. but `validate-methods.py` is not working 
Even did a clean git clone, but `./package-release.sh test ../` fails :)
currently at HEAD: 6f021c0c199419277d0c9d07e21ce12734357fc2

cba to "learn how to python" atm....

**Comment by jp7677** [comment]
mmh, CI checks are just fine https://github.com/jp7677/dxvk-nvapi/commits/master
In case you are running the python script manually, did you add the last param? https://github.com/jp7677/dxvk-nvapi/blob/master/package-release.sh#L57

**Comment by SveSop** [comment]
I dunno what CI checks does or how that helps me.. cos i don't really care :)

Copy of teminal outpu just now:

```
git clone https://github.com/jp7677/dxvk-nvapi.git
Cloning into 'dxvk-nvapi'...
remote: Enumerating objects: 2018, done.
remote: Counting objects: 100% (836/836), done.
remote: Compressing objects: 100% (313/313), done.
remote: Total 2018 (delta 648), reused 629 (delta 511), pack-reused 1182
Receiving objects: 100% (2018/2018), 1.13 MiB | 8.32 MiB/s, done.
Resolving deltas: 100% (1422/1422), done.
~/Temp$ cd dxvk-nvapi/
~/Temp/dxvk-nvapi$ ./package-release.sh release ../
Method validation failed. Please make sure that all implemented NVAPI methods correspond to available methods in the `nvapi_interface_table` header method.

```

**Comment by jp7677** [comment]
Well, every commit triggers a complete clean build on GitHub,  exactly to notify on time if a commit broke compiling.
I did the same in a temporary directory (incl. git submodules update), compiling starts justfine. Which python version do you have (`python --version`)? Here Python 3.9.6 on Fedora, the CI builds run Arch, I guess also quite a new python version.

**Comment by SveSop** [comment]
Ah.. yeah, i think the default for Ubuntu seems to be 2.7.18, but python3 can be installed aswell.. but every now and again with some package upgrades it will switch back to python(2)... So i guess it had switched.
I know this CAN happen from time to time when there is upgrades, and i have to re-run `sudo update-alternatives --config python`.. and this is the output:
`update-alternatives: warning: forcing reinstallation of alternative /usr/bin/python3.8 because link group python is broken`

and viola: python --version = Python 3.8.10

Works fine now.. sorry.. did not think of that "random breakage" being prone to happen (since it DID work before that commit with python 2.7.18).

**Comment by jp7677** [comment]
I just pushed https://github.com/jp7677/dxvk-nvapi/commit/23f249e64f1b1e4a8669c60e6d6957dec8394b9a to at least ensure a better error message.

Ubuntu has a package called `python-is-python3`. That  should take care of most things you did manually.

**Comment by SveSop** [comment]
> I just pushed [23f249e](https://github.com/jp7677/dxvk-nvapi/commit/23f249e64f1b1e4a8669c60e6d6957dec8394b9a) to at least ensure a better error message.
> 
> Ubuntu has a package called `python-is-python3`. That should take care of most things you did manually.
> 
That is well and good... but sadly it seems (for me atleast), this will break my virtualbox-6.1 package (that seems to hinge on the python-is-python2 package for some reason).
[https://forums.virtualbox.org/viewtopic.php?f=7&t=101006](https://forums.virtualbox.org/viewtopic.php?f=7&t=101006)
Can't say if this is relevant.. but i am not about to find out hehe...

**Comment by jp7677** [comment]
I've force-pushed again https://github.com/jp7677/dxvk-nvapi/commit/5d7a17b620cfadbcf426a82cc366161079e71d90

**Comment by jp7677** [comment]
I've finally found some time to try the Batman AK Gameworks features,(aper debris and Interactive Fog/Smoke. The paper debris are indeed there now (very cool!), but the smoke/fog is not visible. I can see that FPS go heavily down with fog/smoke being enabled, so it does something, but no visual difference. 

The logs doesn't contain any super obvious things. With just paper debris being enabled, I can see that `cudart64_55.dll` is loaded at some point and indeed a lot of wine-cuda calls are logged. When just smoke/fog is enabled, there are much less cuda calls and no `cudart64_55.dll` is loaded. But really no idea if this is related.

**Comment by jp7677** [comment]
_I 've deleted my posting about Interactive smoke not working in Arkham Knight. It does work once physx is updated for that game (`protontricks 208650 physx`)._

So I've finally found some time to play with the game works features in Arkham Knight, All works with an updated physx installation, nvcuda from wine staging (plus the `-1` so name fix) and dxvk-nvapi from the physx branch. Thanks @SveSop for all the investigation (and also for providing a bundle with nvcuda and friends)!

**Comment by sfjuocekr** [comment]
@SveSop install the package named "python-is-python3" on Ubuntu if sometimes python2 seems to be used ;)

**Comment by jp7677** [comment]
Hi @SveSop, still missing a unit-test, but otherwise the branch https://github.com/jp7677/dxvk-nvapi/pull/34 should be finally good with the recent header update. It works fine here, but let me know if everything is well for physx from your side.
