### ISSUE TITLE
SetDepthBoundsTest

### ISSUE THREAD

**Issue by jp7677** [jp7677/dxvk-nvapi#4]
Using SetDepthBoundsTest seems to make only marginal or no difference at all with regards to performance / frames per seconds. I'm not sure if this is expected considering it is used quite often. May be there is more to it. 

Looking a bit into the code there is nothing obvious that seems wrong. The DXVK side also seem to do what it should (based on the very limited knowledge I have). The driver is also doing something with it since hacking difference values for min/max bounds does effect the output and fps.

A desperate attempt to use `VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE_EXT` yielded no difference, at least with one bechmark that uses DBT. I'm attaching that patch here anyway for not getting lost.

[dbt-dynamic.patch.txt](https://github.com/jp7677/dxvk-nvapi/files/5977725/dbt-dynamic.patch.txt)

**Comment by jp7677** [comment]
Just for reference, those engine / games use `SetDepthBoundsTest` and do work fine together with this project:
- Unreal Engine 4, e.g. Assetto Corsa Competizione
- GTA V
- Monster Hunter Benchmark
But unfortunately no or just marginal improvements is seen.

**Comment by Dragon31337** [comment]
Did you try Far Cry 5?

**Comment by jp7677** [comment]
@Dragon31337 i don’t have FC5 in my library, so no, unfortunately not.
That said, feel free to test this title yourself and report back, I would be curious about your findings.

**Comment by Dragon31337** [comment]
I've tried to build this project on my windows machine today with both VS2019 and clang 11. Both have failed with different errors.

**Comment by jp7677** [comment]
You could try the compiled version from the package here https://github.com/jp7677/dxvk-nvapi/releases/tag/v0.2.2

**Comment by Dragon31337** [comment]
I do not see it loaded at all on windows. Looks like runtime only loads it from the system root subfolder and ignores the one placed next to the executable. If I replace it in %SystemRoot%\System32 I see it loading but still no output. I will take a look at it later.

**Comment by Dragon31337** [comment]
I see a nice boost with DBT on Assetto Corsa Competizione in 4k with nvapi trick enabled, as it uses SBT quite heavily. ~5% on 30 series card.

**Comment by jp7677** [comment]
Wow nice. This is on Windows?
ACC was the reason I started this, but on Linux I’m still not sure if it really improves.

**Comment by Dragon31337** [comment]
Yes, but it's on windows, but with DXVK and DXVK-NVAPI. Make sure you place built nvapi64.dll in the system root folder (C:\WIndows\Sysytem32\), this is the only location where app with NVAPI SDK picks it up from. I would expect to see the same gains on Linux as well, I did not check yet.

**Comment by Dragon31337** [comment]
you can capture a frame with Nsight tools and replay a frame in the loop for perf testing.

**Comment by jp7677** [comment]
Thanks a lot for the provided info, cool to read that. Are you in a position to also test on Linux. It would be really cool to have that performance win confirmed there as well.

**Comment by Dragon31337** [comment]
I'm sorry, I did not update. DBT is confirmed to be working on Linux with roughly the same gains as on windows.

**Comment by jp7677** [comment]
Thanks a lot for the confirmation. Seems that everything works as intended. I guess we can close this.
