### ISSUE TITLE
Can you make new build ?

### ISSUE THREAD

**Issue by liberodark** [jp7677/dxvk-nvapi#44]
Hi

Can you make new build 0.5 for example because your last release is old.
Some change have been make.

Best Regards

**Comment by jp7677** [comment]
I'm planning to this once things have settled a bit. In the mean time, feel free to use a build from CI: https://github.com/jp7677/dxvk-nvapi/actions/workflows/artifacts.yml?query=branch%3Amaster or use Proton Experimental which uses a very recent development build.

**Comment by jp7677** [comment]
Took a bit more time, but here we are: https://github.com/jp7677/dxvk-nvapi/releases/tag/v0.5
