### ISSUE TITLE
[question] Reflex support possible?

### ISSUE THREAD

**Issue by aufkrawall** [jp7677/dxvk-nvapi#52]
Is Reflex support possible within dxvk-nvapi's scope, or would there be additional work (like the shim DLLs for DLSS by Nvidia) required to make it work on Linux?

**Comment by K0bin** [comment]
What does Reflex even do? I can't find anything specific.

**Comment by aufkrawall** [comment]
I don't know anything more than what they state on the Reflex dev site, which unfortunately is not much: https://developer.nvidia.com/reflex/get-started

The interesting part would be the low latency mode, the tooling stuff for latency measurements imho not so much.
E.g. Deathloop is a game with Reflex that can run on Linux. Reflex helps quite a lot for reducing input lag, which is also nice when playing just the single player mode. I have no idea if it even requires the help of the driver to achieve the latency reduction.

**Comment by K0bin** [comment]
On the D3D9-11 side you could reduce the amount of prepared frames which would help to reduce latency. (DXVK has config options for that). I think one mode in the Nvidia Windows driver also synchronizes with the GPU every frame.

No idea about anything else.

**Comment by aufkrawall** [comment]
Yeah, we don't have an equivalent in vkd3d-proton. :(
AMD's Anti-Lag on Windows also works with D3D12, whereas Nvidia's driver latency reduction mode does not. But some D3D12 and also Vulkan games have Reflex. According to Battle(non)sense's input to pixel measurements, Reflex is better though than Anti-Lag or Nvidia "NULL", as it reduces latency even further by still having just a moderate performance hit. It really helps a lot in Deathloop, Fortnite or Rainbow Six Siege. I'm not sure if there even is a DLL in the games' folder that can be linked to Reflex.

**Comment by aufkrawall** [comment]
> Because that's up to the application to decide with D3D12 and Vulkan. The concept of prerendered frames doesn't exist in D3D12.

I don't dispute that, yet AMD driver devs somehow managed to implement it for D3D12. I tested Anti-Lag in a bunch of D3D12 games like Hitman 2, Shadow of the Tomb Raider or Horizon Zero Dawn and it worked really well. If this would be doable for vkd3d-proton in a similar fashion? I have no idea. Of course I won't disagree that this by far shouldn't be the top priority. Hopefully Reflex support is more doable. :)

**Comment by aufkrawall** [comment]
When switching it on and off, it really makes a lot of a difference for input lag (without any special display device). Especially when fps are lower and games would have CPU prerender of 3 frames otherwise (completely bonkers). Afaik Anti-Lag & "NULL" limit to ~0.5 frames of CPU prerender, whereas Reflex is ~0. Deathloop has an option to reduce latency apart from Reflex, which probably is prenderlimit 1, but Reflex really still makes a noticeable difference on top. I don't know if it also optimizes input processing in some additional way.

Well, hopefully Nvidia can shed some light on Reflex Linux support at some point. :(

**Comment by SveSop** [comment]
Is this an ingame option that is "grayed out" when running the game through Wine/Proton? (And thus would somehow require a NvAPI call?)

Just watched Linus [https://www.youtube.com/watch?v=aL5YTWRpzoA](https://www.youtube.com/watch?v=aL5YTWRpzoA) and it seems that what you use this for - when having the available hardware like mouse, monitor and gpu - is to measure the latency, and then enable/disable various options until you find what gives you the best (least) inputlag. Games having pre-defined "optimum settings" or options, would probably work just aswell for us.. unless ofc it is like i asked above, something unavailable as an option when running under wine/proton. (I don't own any of the games in question, so i cant test this).

I do agree that it would be awesome to be able to view this when playing a game under wine/proton, cos the same settings in windows might need other/different options for Linux... however it very much seems like it is really connected to the driver's overlay functions, something that is not really available for the Linux driver at all. I cannot imagine in any near future where this would be available for Linux tbh.

Just to conclude my (mis)understanding of this:
1. Reflex is a system to measure latency. Monitor/mouse+++ and display this on-screen
2. This is a proprietary nVidia thing
3. Game dev's may use this system to create pre-defined "reflex optimized" setting options for the game (using the SDK)
4. Enabling/disabling said options DOES make a difference regardless of having the correct monitor/mouse
5. It is currently nothing available that makes this measure system work when running under wine/proton

The following questions is raised:
1. Does games with pre-defined Reflex options (ingame settings) not change anything, or are these options unavailable for wine/proton?
2. Would buying one of these "Reflex enabled monitors" actually make it work in Linux? (USB driver talking to the GPU driver with non-existing game-overlay in Linux atm).
3. Would it really help much if we get 40-100ms mouselatency added when wineserver is cpu starved anyway? (Sure.. everything would help i suppose)

I tend to get a bit long winded at times, but i can see quite a few elements completely out of scope from what "we" do with DXVK-NVAPI atm tho... Unless ofc the answer to the first question is "It is grayed out, and probably requires a positive NvAPI call to be enabled", cos faking a reply would probably be easy enough if it would mean the options tweaked some game related settings under the hood (that does not require the driver to drastically change something).

**Comment by aufkrawall** [comment]
[dxvk-nvapi.log](https://github.com/jp7677/dxvk-nvapi/files/7376236/dxvk-nvapi.log)

**Comment by aufkrawall** [comment]
The Reflex option now is available in the game's menu. :)
However, I think it doesn't do anything, as I can't notice any difference regarding input lag (unlike on Windows). Here is a new log:
[dxvk-nvapi.log](https://github.com/jp7677/dxvk-nvapi/files/7376887/dxvk-nvapi.log)

**Comment by jp7677** [comment]
> Yeah, it is quite unknown so far since no public headers with the functions is released. 

All three methods _are_ in the public headers.

**Comment by SveSop** [comment]
Do i understand the dxvk-nvapi testsuite so that it creates a D3D device (via dxgi) when testing some of the NvAPI_D3D12_ calls? If so.. i wonder if a test for those 3 "suspected" calls could be written that would provide SOME useful reply when run in windows?

It would fail (for now) when run with wine/proton, but perhaps it could be used for figuring out how they work in windows with the actual nvapi lib?

**Comment by ishitatsuyuki** [comment]
For anyone who is interested in Reflex support on Linux, please take a look at my project https://github.com/ishitatsuyuki/LatencyFleX, hooked up into games through NvAPI. It can be installed by replacing and adding a few wine libraries, including DXVK-NVAPI.

It does not use any NVIDIA SDK or proprietary code apart from the binding interface. It's possible that it's better or worse than Reflex, but so far as it has been providing satisfactory results for me. (I'm testing on an AMD graphics card with DXVK vendor ID overrides, so let me know if there are any NVIDIA specific issues.)

**Comment by jp7677** [comment]
> For anyone who is interested in Reflex support on Linux, please take a look at my project https://github.com/ishitatsuyuki/LatencyFleX, hooked up into games through NvAPI. It can be installed by replacing and adding a few wine libraries, including DXVK-NVAPI.
> 
> It does not use any NVIDIA SDK or proprietary code apart from the binding interface. It's possible that it's better or worse than Reflex, but so far as it has been providing satisfactory results for me. (I'm testing on an AMD graphics card with DXVK vendor ID overrides, so let me know if there are any NVIDIA specific issues.)

Thanks a lot. This looks certainly promising, I’ll keep your project in the back of my mind!

**Comment by jp7677** [comment]
The LatencyFlex PR is merged, enabling Reflex should now make a difference when LatencyFlex (https://github.com/ishitatsuyuki/LatencyFleX) is properly set up.

**Comment by jp7677** [comment]
All credits to @ishitatsuyuki !
