### ISSUE TITLE
Shadow of the Tomb Raider

### ISSUE THREAD

**Issue by sfjuocekr** [jp7677/dxvk-nvapi#53]
Game needs WINEDLLOVERRIDES=nvngx= to get past the initial crash after the first loading screen.

Afterwards the game does not want to enable DLSS, this is the log:

```
---------- 2021-10-31 04:15:01 ----------
DXVK-NVAPI experimental-6.3-20211027 (SOTTR.exe)
NvAPI Output: \\.\DISPLAY1
NvAPI Device: NVIDIA GeForce RTX 3060 (495.44.0)
NvAPI_Initialize: OK
NvAPI_QueryInterface 0x33c7358c: Unknown function ID
NvAPI_QueryInterface 0x593e8644: Unknown function ID
NvAPI_QueryInterface NvAPI_Stereo_IsEnabled: Not implemented method
NvAPI_QueryInterface NvAPI_Stereo_SetDriverMode: Not implemented method
NvAPI_DISP_GetGDIPrimaryDisplayId: OK
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_Mosaic_GetDisplayViewportsByResolution: Mosaic not active
NvAPI_QueryInterface 0xad298d3f: Unknown function ID
NvAPI_Initialize: OK
NvAPI_QueryInterface NvAPI_DRS_CreateSession: Not implemented method
NvAPI_EnumPhysicalGPUs: OK
NvAPI_GPU_GetAdapterIdFromPhysicalGpu: OK
NvAPI_QueryInterface 0xf2400ab: Unknown function ID
NvAPI_EnumPhysicalGPUs: OK
NvAPI_GPU_GetArchInfo: OK
NvAPI_SYS_GetDriverAndBranchVersion: OK
NvAPI_QueryInterface 0xa782ea46: Unknown function ID
NvAPI_QueryInterface NvAPI_DRS_FindApplicationByName: Not implemented method
NvAPI_QueryInterface NvAPI_DRS_DestroySession: Not implemented method
NvAPI_Initialize: OK
NvAPI_QueryInterface NvAPI_D3D11_EnumerateMetaCommands: Not implemented method
NvAPI_Initialize: OK
NvAPI_D3D11_CreateSamplerState: OK
NvAPI_EnumPhysicalGPUs: OK
NvAPI_GPU_GetAdapterIdFromPhysicalGpu: OK
NvAPI_EnumPhysicalGPUs: OK
NvAPI_GPU_GetArchInfo: OK
NvAPI_SYS_GetDriverAndBranchVersion: OK
NvAPI_D3D11_IsNvShaderExtnOpCodeSupported 12 (NV_EXTN_OP_FP16_ATOMIC): OK
NvAPI_D3D11_IsNvShaderExtnOpCodeSupported 12 (NV_EXTN_OP_FP16_ATOMIC): OK
NvAPI_QueryInterface NvAPI_D3D_QueryModifiedWSupport: Not implemented method
NvAPI_EnumPhysicalGPUs: OK
NvAPI_GPU_GetAdapterIdFromPhysicalGpu: OK
NvAPI_EnumPhysicalGPUs: OK
NvAPI_GPU_GetArchInfo: OK
NvAPI_SYS_GetDriverAndBranchVersion: OK
NvAPI_QueryInterface NvAPI_D3D12_EnumerateMetaCommands: Not implemented method

```

**Comment by jp7677** [comment]
Thanks for the report. If you use `WINEDLLOVERRIDES=nvngx=`, you are kind-of disabling DLSS. So  it is expected that DLSS is not available with that option.

The logs are with `nvngx` disabled? If yes, could you please post logs without that option? May be that gives some clues where the crash is coming from.

Just to be sure, this is with DLSS 2.x?

PS: Please properly format the logs here in github or just attach the log file. Reading the logs like this does not really motivates to go through them.

**Comment by sfjuocekr** [comment]
Ah ok, I was under the impression that disabling nvngx would disable DLSS 1.x from trying to initialize. SotR should be updated to DLSS 2.x.

[dxvk-nvapi.txt](https://github.com/jp7677/dxvk-nvapi/files/7449965/dxvk-nvapi.txt)

From running the game with:

DXVK_NVAPI_LOG_LEVEL=info PROTON_ENABLE_NVAPI=1 PROTON_HIDE_NVIDIA_GPU=0 PROTON_LOG=1 %command%

[steam-750920.txt](https://github.com/jp7677/dxvk-nvapi/files/7449969/steam-750920.txt)

From that log I can tell it does try to load nvngx-dlss.dll.

**Comment by jp7677** [comment]
Thanks for the logs and also for reformatting the initial posting ;).

Well, the dxvk-nvapi logs are identical as far as I can see. That said. I don't see any typical DLSS calls like `NvAPI_D3D12_CreateCubinComputeShader` or `NvAPI_D3D11_CreateCubinComputeShader`.  So it crashes before that or within those calls. Do you get the same with D3D12 and D3D11? Does the DXVK or VKD3D-Proton logs contains anything interesting?

**Comment by sfjuocekr** [comment]
[steam-750920.log](https://github.com/jp7677/dxvk-nvapi/files/7457114/steam-750920.log)
[dxvk-nvapi.log](https://github.com/jp7677/dxvk-nvapi/files/7457115/dxvk-nvapi.log)
[vkd3d.log](https://github.com/jp7677/dxvk-nvapi/files/7457116/vkd3d.log)
[SOTTR_dxgi.log](https://github.com/jp7677/dxvk-nvapi/files/7457126/SOTTR_dxgi.log)
[SOTTR_d3d11.log](https://github.com/jp7677/dxvk-nvapi/files/7457127/SOTTR_d3d11.log)

More logs for you, game started in DX11 mode there and the same behavior is observed with DX12.

I do not see it call for those two functions either.

It might have todo with the launcher not detecting DLSS?

For example if I enable DXR, the launcher detects it and will enable it. But it does not work, in-game the option is grayed out as well if I start it without setting ray traced shadows in the launcher.

**Comment by jp7677** [comment]
Unfortunately I don't see any traces of something of interest. I don't think DXVK-NVAPI is doing anything wrong here, but yeah, no idea either about what is going on based on the logs.

**Comment by jp7677** [comment]
PS: just to be sure, you get the same behavior for DLSS you are describing also without passing `dxr11` into vkd3d-proton?

**Comment by sfjuocekr** [comment]
Yes.

**Comment by jp7677** [comment]
This video seem to indicate that DLSS works with SOTTR (and also with its predecessor) https://www.youtube.com/watch?v=RThWsTavn0Q&ab_channel=LinuxGameCast

**Comment by sfjuocekr** [comment]
Correct, after realizing DLSS was never initialized I noticed that the game had disabled DLSS completely as there were issues with it.

The latest update did indeed make it work!

**Comment by gardotd426** [comment]
I can confirm that DLSS does indeed work with the latest update, however I wouldn't recommend it as with my 3090 performance at 1440p with DLSS Performance mode is still 7% slower than the native version which doesn't even have DLSS, and this is **without** Ray Tracing as Ray Tracing does **not** work, so there is no reason to use this over native. Except for multiplayer, I guess.

**Comment by jp7677** [comment]
Yes, I agree. It is good to know for science that DLSS works with the Windows version, but Ferals port is excellent and should absolutely be preferred.

**Comment by aufkrawall** [comment]
Performance of the Vulkan port really is great. Unfortunately the Linux port has one big, ugly caveat: Mouse input seems to have some kind of polling rate at 30Hz or so, which makes moving the camera via mouse look choppy. This is really obtrusive with perfect vsync or VRR. Typical Linux port issue. :(

**Comment by gardotd426** [comment]
Weird. I can't reproduce that on my 165Hz monitor and 1000Hz mouse (though
this isn't really the forum for diving into why that might be). Anyway, I
guess it's good for people to know who do run into this issue.

**Comment by sfjuocekr** [comment]
I observe no such issues with mouse input on either version. Try disabling display compositing while the game is running, it can interfere with VSYNC.
