### ISSUE TITLE
Add an envar to reject nvapi usage when a non-Nvidia card is in use

### ISSUE THREAD

**Issue by tannisroot** [jp7677/dxvk-nvapi#58]
See https://github.com/lutris/lutris/issues/3883

**Comment by jp7677** [comment]
Thanks for the report. Thinking about this, we should even go forward and reject non NVIDIA GPUs by default and allow reporting non NVIDIA GPUs (the current behavior) only when a certain env var is set.

**Comment by tannisroot** [comment]
Yeah that would be preferred in Lutris' usecase.

**Comment by jp7677** [comment]
The current git version of DXVK-NVAPI should be good now for this use case. I don't know if you or the original reporter is able to test this, if yes, please let me know if all is indeed good.
