### ISSUE TITLE
GitHub Actions CI (+artifacts) support..

### ISSUE THREAD

**Issue by oscarbg** [jp7677/dxvk-nvapi#6]
Hi,
interesting library.. can we get like DXVK and VKD3D GitHub actions CI support so we don't have to wait for (point) releases for  prebuilt binaries..
thanks..

**Comment by jp7677** [comment]
Thanks for your interest and suggestion. Yeah, setting up CI/CD is a good idea. Do note though, contrary to DXVK VKD3D this project moves way slower. Currently you won’t mis much if you just grab the latest release.

**Comment by jp7677** [comment]
Github actions are added now with https://github.com/jp7677/dxvk-nvapi/pull/9
