### ISSUE TITLE
DLSS don't work in Rise of the Tomb Rider

### ISSUE THREAD

**Issue by weter11** [jp7677/dxvk-nvapi#62]
Hi! I tried to install windows version with DLSS support to check how it working on my book {5800H + RTX3070}. In a simple window with game preferences I can choose DLSS, but then in a game it simply can't be changed, but not grayed. Because of optimus nature I tried to blacklist AMD iGPU, update nvapi to v0.5.1 and nvngx_dlss to 2.3.5, insert '__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia PROTON_ENABLE_NVAPI=1 PROTON_HIDE_NVIDIA_GPU=0 %command%' in a steam game options. 
Log always report:

`DLSS support test, code = 0x00000001, info: NVSDK_NGX_Result_Success`
`Disabling DLSS as it is not supported on non Nvidia cards`

I'm using latest Proton experimental in Steam preferences. For comparison Hellblade is working flawlessly with DLSS and DXR in DX12 mode and with DLSS in DX11 mode with only 1 option PROTON_ENABLE_NVAPI=1 %command%.

[Rise of the Tomb Raider optimus.log](https://github.com/jp7677/dxvk-nvapi/files/7777137/Rise.of.the.Tomb.Raider.optimus.log)
[steam-391220.log](https://github.com/jp7677/dxvk-nvapi/files/7777138/steam-391220.log)
[Rise of the Tomb Raider external display blacklist iGPU.log](https://github.com/jp7677/dxvk-nvapi/files/7777139/Rise.of.the.Tomb.Raider.external.display.blacklist.iGPU.log)

**Comment by jp7677** [comment]
Thanks for the report.
Could you please additionally set `DXVK_FILTER_DEVICE_NAME`? See https://github.com/doitsujin/dxvk#device-filter . May be that convinces the game to really just recognize your NVIDIA card. Not sure though if that really helps, but lets start by ruling out the game trying to use your other card.

**Comment by jp7677** [comment]
Ah wait, looking at your last log, it sees AMD as the vendor of your nvidia card. Did you had disabled the DXVK nvapi hack? See https://github.com/doitsujin/dxvk/blob/master/dxvk.conf#L51

**Comment by weter11** [comment]
But dxvk.conf is absent in Steam proton, I tried search for dxvk.conf on my system and don't find it anywhere in any folder. I tried  disable hack in game options window with dxgi.nvapiHack=1 and DXGI.NVAPIHACK=1 but game dont start. Also game can't start without Steam for example in Lutris.

**Comment by jp7677** [comment]
Unfortunately you can’t control the DXVK nvapi hack by environment variable. The easiest way is to create the DXVK configuration file, set the nvap setting in it and use an environment variable to point to it. See https://github.com/doitsujin/dxvk/wiki/Configuration

**Comment by weter11** [comment]
Looks like **PROTON_HIDE_NVIDIA_GPU** don't provide the same functionality as dxgi.nvapiHack.
So I insert **DXVK_CONFIG_FILE=/home/wer/.local/dxvk.conf DXVK_FILTER_DEVICE_NAME="NVIDIA GeForce RTX 3070 Laptop" PROTON_ENABLE_NVAPI=1  %command%** to game settings window. **dxvk.conf** contain only
`dxgi.nvapiHack = False`
And voila DLSS working now, thanks to your support.
Its strange, but DLSS don't provide additional performance, 100fps w/o any AA and 104 with DLSS quality, also GPU heavily underclocked, sometimes only 55-65% load.
I have Hellblade in my library, but DLSS and DXR working w/o any additinal settings, except PROTON_ENABLE_NVAPI=1.
Thanks for help! Maybe it's good to add this information to readme?

**Comment by jp7677** [comment]
Yeah, there are unfortunately several places that hide an Nvidia GPU and all switches just affect a single place. Also games might use different places to determine on which GPU they are running, seems like RotTR is a bit more picky. Anyway, cool to read that your issue is solved!

Regarding performance, may be you are CPU limited now considering that you GPU is now under-utilized?

Actually I tried to mention the DXVK configuration file here https://github.com/jp7677/dxvk-nvapi#proton . Do you have a suggestion on how to improve that section?

**Comment by weter11** [comment]
I think that, if someone have a problem with a game like this, temporarily add to #proton 
"If a game can't provide DLSS support with standard option **PROTON_ENABLE_NVAPI*=1*, add adiitionally **dxgi.nvapiHack = False** to a file dxvk.conf  with variable **DXVK_CONFIG_FILE=$HOME/dxvk.conf**  as game launch argument in Steam.
Because by default Steam don't generate any dxvk.conf.
