### ISSUE TITLE
Horizon Zero Dawn does not launch with PROTON_ENABLE_NVAPI=1

### ISSUE THREAD

**Issue by ProjectSynchro** [jp7677/dxvk-nvapi#68]
Hi, I figured this issue would be applicable here. 

Ever since Horizon Zero Dawn has added DLSS, FSR, etc. there was a rendering bug in respect to vkd3d-proton. 

This is now fixed, but it appears that enabling dxvk-nvapi in order to enable DLSS causes the game to crash on launch. I have also set `dxgi.nvapiHack = False` with dxvk (not sure if this applies here or not).

Here is a log file after running the game with `PROTON_LOG=1 PROTON_ENABLE_NVAPI=1 PROTON_HIDE_NVIDIA_GPU=0 gamemoderun %command%`:
[steam-1151640.log](https://github.com/jp7677/dxvk-nvapi/files/7931759/steam-1151640.log)

Snooping around my Proton Experimental files I see a build artefact that lists the git sha of the version of dxvk-nvapi being used:
`acbcf35e327f2d189e1a9322bc1359a22d36cf6a dxvk-nvapi (v0.4-37-gacbcf35)` was this potentially fixed in [dxvk-nvapi 0.5](https://github.com/jp7677/dxvk-nvapi/releases/tag/v0.5)?

Let me know if I can provide anything else or do some testing (might need some instructions as to where to stick any related DLLs.)

**Comment by jp7677** [comment]
Could you please try to fetch DXVK-NVAPI logs (https://github.com/jp7677/dxvk-nvapi#tweaks-debugging-and-troubleshooting), lets see if something interesting comes up. You might also indeed try a DXVK-NVAPI build from master (https://github.com/jp7677/dxvk-nvapi/actions/runs/1736351655 , also see https://github.com/jp7677/dxvk-nvapi#proton).

Some additionally ideas:
What happens if you set the `dxgi.nvapiHack` to false but don't set `PROTON_ENABLE_NVAPI`? Additionally, what happens if you explicitly disable nvngx (`WINEDLLOVERRIDES=nvngx=` and/or `WINEDLLOVERRIDES=_nvngx=`)? 
The logs show a lot of d3dcompiler warning, what happens if you install native `d3dcompiler47` using winetricks?

**Comment by phush0** [comment]
For me it is working with same env vars on Nvidia Optimus laptop with RTX 5000 GPU and proton experimental. You can try use proton-ge-custom which will install d3dcompiler  where it needs to be. If you still have crashes and you use mangohud try to disable it too.

**Comment by ProjectSynchro** [comment]
> Could you please try to fetch DXVK-NVAPI logs (https://github.com/jp7677/dxvk-nvapi#tweaks-debugging-and-troubleshooting), lets see if something interesting comes up.

I enabled logging without any further modifications (only installed mfc140 so the game would launch if it worked)
Here is that log: [dxvk-nvapi.log](https://github.com/jp7677/dxvk-nvapi/files/7942475/dxvk-nvapi.log)
Interesting lines:
```
NvAPI_QueryInterface 0xad298d3f: Unknown function ID
NvAPI_QueryInterface 0x33c7358c: Unknown function ID
NvAPI_QueryInterface 0x593e8644: Unknown function ID
NvAPI_QueryInterface NvAPI_D3D_ImplicitSLIControl: Not implemented method
NvAPI_QueryInterface NvAPI_DRS_CreateSession: Not implemented method
NvAPI_QueryInterface 0xf2400ab: Unknown function ID
```
> What happens if you set the dxgi.nvapiHack to false but don't set PROTON_ENABLE_NVAPI? 

The game seems to launch as expected (with mfc140 installed), but does not show any DLSS options.

> Additionally, what happens if you explicitly disable nvngx (WINEDLLOVERRIDES=nvngx= and/or WINEDLLOVERRIDES=_nvngx=)?

With `WINEDLLOVERRIDES=nvngx=` the game does not launch
Log here: [dxvk-nvapi-disable-nvngx.log](https://github.com/jp7677/dxvk-nvapi/files/7942541/dxvk-nvapi-disable-nvngx.log)

With `WINEDLLOVERRIDES=_nvngx=` the game launches with no DLSS options in the menus
Log here: [dxvk-nvapi-disable-_nvngx.log](https://github.com/jp7677/dxvk-nvapi/files/7942558/dxvk-nvapi-disable-_nvngx.log)

> The logs show a lot of d3dcompiler warning, what happens if you install native d3dcompiler47 using winetricks?

No changes with d3dcompiler_47 installed via protontricks

> You might also indeed try a DXVK-NVAPI build from master (https://github.com/jp7677/dxvk-nvapi/actions/runs/1736351655 , also see https://github.com/jp7677/dxvk-nvapi#proton).

Last and the solution:
Using the build you linked from that workflow run on master launches the game and appears to be working. I still see some warnings about unimplemented functions in the log but it appears to be working correctly.
See log: [dxvk-nvapi-master.log](https://github.com/jp7677/dxvk-nvapi/files/7942625/dxvk-nvapi-master.log)
 
It looks like this is a case of waiting for downstream to pull new changes.. Thanks for helping me debug this a bit and apologies for the extra noise at the very least I'll know what to look for if I suspect NVAPI is the culprit of any issues in the future. For now it looks like I'll just have to run these DLLs if I want to play the game on Proton Experimental.

**Comment by jp7677** [comment]
@ProjectSynchro thanks for the heads up and glad to read that DXVK-NVAPI from master solves this.

**Comment by jp7677** [comment]
Hi @ProjectSynchro , I’ve pushed a tiny change to master that should effectively change nothing in HZD except a log statement. Could you please try this version and report if the game reacts weird now or if I somehow borked it? Recent binary from CI: https://github.com/jp7677/dxvk-nvapi/actions/runs/1754732679

**Comment by ProjectSynchro** [comment]
> Hi ProjectSynchro , I’ve pushed a tiny change to master that should effectively change nothing in HZD except a log statement. Could you please try this version and report if the game reacts weird now or if I somehow borked it? Recent binary from CI: https://github.com/jp7677/dxvk-nvapi/actions/runs/1754732679

Hey @jp7677, nothing seems to have broken when using the linked CI build from master.
Peeking into the log file shows `NvAPI_D3D_ImplicitSLIControl: OK` so it appears that function/method you implemented is working :smile: 
It looks like there are only 3 other unimplemented methods (unsure how much impact, if any these really make)

```
NvAPI_QueryInterface NvAPI_DRS_CreateSession: Not implemented method
NvAPI_QueryInterface NvAPI_DRS_FindApplicationByName: Not implemented method
NvAPI_QueryInterface NvAPI_DRS_DestroySession: Not implemented method
```

Here's the log from my test run (if it's useful):
[dxvk-nvapi.log](https://github.com/jp7677/dxvk-nvapi/files/7951958/dxvk-nvapi.log)

**Comment by jp7677** [comment]
Thanks for the confirmation!
Yeah, HZD wants to disable SLI, dxvk-nvapi just acknowledges this now (since there is no SLI on Linux). Glad to hear that HZD does not do any weird things (like using a lot of other nvapi methods) after that call succeeded.

Those other methods are about driver settings / application profiles, those are not supported with this nvapi implementation. Fortunately all games seem to deal with this correctly.
