### ISSUE TITLE
Question about latencyflex integration.

### ISSUE THREAD

**Issue by Bitwolfies** [jp7677/dxvk-nvapi#75]
(Sorry to ask in an issue, didn’t see any other contact)

The newest version of DXVK-NVAPI now includes “Forwarding to latencyflex”, does this mean we only need the latencyflex vullkan layer, and none of the wine stuff? (Sorry to ask and thanks for making this!

**Comment by jp7677** [comment]
No worries, perfectly cool to ask here.

The latest DXVK-NVAPI release implements the Reflect entry points and forwards those calls to LatencyFlex when the LatencyFlex library has been found. It does not integrate any LatencyFlex code, so you still need to setup the Vulkan layer and the Wine extension as described here https://github.com/ishitatsuyuki/LatencyFleX#installation. Though you don’t need a DXVK-NVAPI version from master anymore or a build from the fork that had been created initially.

**Comment by Bitwolfies** [comment]
Thanks a lot for the response, good to know you're doing what you can to support the project. Shame I still have to manually move the wine extensions per prefix. but its early days and it could change one day, but I don't think that's a problem for you to solve :)
