### ISSUE TITLE
God of War crash

### ISSUE THREAD

**Issue by K0bin** [jp7677/dxvk-nvapi#76]
God of War recently received an update that causes it to crash when NVAPI is enabled.

`PROTON_ENABLE_NVAPI=1`=> crash
`PROTON_ENABLE_NVAPI=0`=> works

There's a couple of unknown functions mentioned in the log but they don't seem to be part of the open source NVAPI headers as far as I can tell.

[dxvk-nvapi.log](https://github.com/jp7677/dxvk-nvapi/files/8337831/dxvk-nvapi.log)

**Comment by jp7677** [comment]
Thanks for the report and for providing the logs. Though unfortunately there is nothing really obvious in it.

Do you see the same behavior with lets say DXVK-NVAPI v0.5.0  (https://github.com/jp7677/dxvk-nvapi/releases/tag/v0.5)? There are some DRS (driver settings) calls in that logs which I added (stubbed) recently , may be I screwed up there.

Just to be sure, the crash happens inside GoW and nvapi is not part of the stack trace?

**Comment by K0bin** [comment]
It only crashes with the NVAPI dll shipped by Proton Experimental Bleeding Edge. If I remove that DLL with either your 1.5.3 release build or my own build of master, it works.

**Comment by jp7677** [comment]
Nice find. Is only beading edge affected or does normal Proton or Proton Experimental have the same issue?

**Comment by K0bin** [comment]
Normal Proton is fine. I haven't tried regular experimental.

**Comment by jp7677** [comment]
Do you have the chance to try regular experimental? Experimental and bleading-edge contain the same DXVK-NVAPI source, I guess having a differences (or not) between those two versions makes it easier to pinpoint the actual issue.

**Comment by K0bin** [comment]
Experimental works.

**Comment by jp7677** [comment]
@K0bin @ivyl Proton beading-edge should be good again with DXVK-NVAPI from master. Thanks a lot for finding and helping to resolve this issue!

**Comment by K0bin** [comment]
Nice, great work everyone. :)

**Comment by ivyl** [comment]
[This has just landed in the bleeding-edge](https://github.com/ValveSoftware/Proton/commits/experimental-bleeding-edge-7.0-12609-20220328-p974ec7-w8fb04d-debdaf9-v2e8fb2). I think that manual bumps for dxvk-nvapi are good enough, but let me know if you disagree and would like to have automated updates like we have for vkd3d-proton and dxvk.

**Comment by jp7677** [comment]
Thanks a lot! Manual bumps are perfectly fine, dxvk-nvapi moves way slower than dxvk or vkd3d-proton.
