### ISSUE TITLE
[Compatibility] Batman Arkham Asylum Unofficial Launcher

### ISSUE THREAD

**Issue by ThisNekoGuy** [jp7677/dxvk-nvapi#83]
- Related to: https://github.com/Frogging-Family/wine-tkg-git/issues/683

[BmLauncher_dxgi.log](https://github.com/jp7677/dxvk-nvapi/files/8445632/BmLauncher_dxgi.log)
[steam-35140.log](https://github.com/jp7677/dxvk-nvapi/files/8445651/steam-35140.log)

# Description
[This unofficial game launcher makes use of NvAPI](https://github.com/neatodev/BmLauncher) but doesn't work with dxvk-nvapi supposedly due to missing implementations

**Comment by jp7677** [comment]
Thanks for the report. Looking at the original code from that project (https://github.com/neatodev/BmLauncher/blob/master/infrastructure/NvidiaWorker.cs), it wants to get and set several driver setttings for this game. DXVK-NVAPI does not support any driver settings, those calls are not implemented or return an error indicating no profile has been found. There are no plans to support this in the future.
The best approach would be to modify the launcher that it just ignores any failing NVAPI settings and in that case e.g. disables the related options in the UI.

**Comment by ThisNekoGuy** [comment]
Alright, thanks for letting me know
I created an issue report over there suggesting that

**Comment by ThisNekoGuy** [comment]
The issue was closed  on their end due to a lack of interest in Linux; though, an initial attempt to alleviate the problem was made and did cause progress.

Some NvAPI error handling was implemented but some more is needed in order to get past the launcher's initialization.
