### ISSUE TITLE
Why do i have to confirm my identity to build this via aur

### ISSUE THREAD

**Issue by LethalManBoob** [jp7677/dxvk-nvapi#95]
Remove this "feature" asap. thanks

**Comment by jp7677** [comment]
This repository does not provide any distribution packages, so here is no "feature" to remove. 
Since you provided no further details (I don't use Arch), I don't know where to direct you with your question.

PS: Please also reconsider your accusative tone in your request, that doesn't really motivates to respond.

**Comment by LethalManBoob** [comment]
==> Starting prepare()...
Committer identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'joseph@archlinux.(none)')
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'dxvk-nvapi-mingw-0.5.4-1': 
error: packages failed to build: dxvk-nvapi-mingw-0.5.4-1

**Comment by jp7677** [comment]
As stated, I’m not familiar how the aur packaging on Arch works. That said, this looks like the normal git setup steps are missing, may be you just have to follow https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git

**Comment by micwoj92** [comment]
This is aur packaging issue, I've reported this on package page.

**Comment by jp7677** [comment]
For reference: https://aur.archlinux.org/cgit/aur.git/commit/?h=dxvk-nvapi-mingw&id=6db8fdac3b666da96cab7a97eeb184eb68407ef1
